#!/usr/bin/env perl
use strict;
use File::HomeDir;
use Path::Class;
use Git::Repository;
use String::Flogger qw/ flog /;
use v5.10;

my $home = dir home;
check( $home->subdir( $_ ) ) for qw/ Downloads Desktop Documents github /;

sub check {
    my $root = shift;
    return unless -d $root;
    for ( sort $root->children( no_hidden => 1 ) ) {

        #--------------------
        # 需要清理的仓库
        if ( -d $_ && -d $_->subdir( '.git' ) ) {
            my $repos  = Git::Repository->new( work_tree => "$_" );
            my $status = $repos->run( 'status' );
            next if $status =~ /working tree clean/;
            say flog [ 'M %s', $_->basename ];
        }

        #--------------------
        # 需要清理的文件
        else {
            print "? $_\n";
        }
    }
}
