#!/usr/bin/env perl
use strict;
use WWW::Mechanize;
use File::HomeDir;
use Path::Class;
local $| = 1;

#-------------------------------------------------------------------------
my $kinds = {
    'retina_macbook_pro_15' => '3840x2400',
    'new' => '3840x2160',
    'imac_21'               => '1920x1080',
    'imac_5k'               => '5120x2880',
};

#-------------------------------------------------------------------------
my $pages = shift || 999;
# my $kind  = shift || 'imac_5k' || 'retina_macbook_pro_15';
my $kind  = shift || 'new';
my $res   = $kinds->{$kind};

#-------------------------------------------------------------------------
# the ~/Pictures/InterfaceLift dir
my $home = File::HomeDir->my_home;
my $lift_dir = dir( $home, 'InterfaceLift' );
-d $lift_dir || $lift_dir->mkpath;

#-------------------------------------------------------------------------
for my $page ( 1 .. $pages ) {

    my $mech = WWW::Mechanize->new();
    my $url = sprintf 'http://interfacelift.com/wallpaper/downloads/date/widescreen/%s/index%d.html', $res, $page;
    printf STDERR "==> wget page %d for %s\n", $page, $res;

    $mech->get($url);
    my @links = $mech->find_all_links( url_regex => qr/_$res\.jpg/ );
    for (@links) {
        my $url_abs  = $_->url_abs;
        my $basename = ( split /\//, $url_abs )[-1];
        my $file     = $lift_dir->file($basename);

        if ( -f $file and -s $file > 1000000 ) {
            printf "skip %-60s %.2fMB\n", $file->basename, ( ( -s $file ) / 1000000 );
            next;
        }

        -f $file and $file->remove;

        printf "wget %-60s ", $file->basename;
        my $mech = WWW::Mechanize->new();
        $mech->get($url_abs);
        $mech->save_content( $file->stringify );
        printf "%.2fMB\n", ( ( -s $file ) / 1000000 );
    }
}
