#!/usr/bin/env perl
use Dancer2;
use Mojo::File;
use YAML;
use Template;
use Text::Markdown;
use File::Slurp;

my $template = join "\n", <DATA>;

set charset => 'utf8';

get '/' => sub {

    my $dir   = Mojo::File->new( '.' );
    my @files = grep { $_ =~ /\.mm?d/ } $dir->list_tree->each;

    my $vars = {};
    $vars->{files} = \@files;

    my $path = param 'path';
    if ( $path and -f $path ) {
        my $m   = Text::Markdown->new;
        my $md  = read_file( $path, { binmode => ':utf8 ' } );
        my $doc = $m->markdown( $md );
        $vars->{doc}  = $doc;
        $vars->{path} = $path;
    }

    my $html = '';
    Template->new->process( \$template, $vars, \$html );

    return $html;
};

dance;

__DATA__
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <style>
        h1, h2, h3, h4, h5, h6 { margin-bottom: 1.5rem; }
        p { font-size: 1.2rem; line-height: 1.82rem; font-family: Palatino,FreeSerif,Georgia,serif; margin-bottom: 1.2rem; }
        pre { padding: 1.5rem; background: #f6f6f6; border-radius: 1rem; color: #333; margin-bottom: 1.2rem; }
    </style>
</head>
<body>

<div class="container mx-auto">
<div class="row gap-3">
    <div class="col"> 
        [% FOREACH file = files %]
        <div class="my-1 small text-truncate ">
            <a class="text-decoration-none" href="/?path=[% file %]">[% file %]</a>
        </div>
        [% END %]
    </div>
    <div class="col-7"> 
        <div class="text-sm mb-3">[% path %]</div>
        [% doc %]
    </div>
    <div class="col"> 
    </div>
</div>
</div>

</body>
</html>
