#!/usr/bin/env perl
use Dancer2;
use Mojo::File;
use YAML;
use Template;
use Text::Markdown;
use File::Slurp;

my $template = join "\n", <DATA>;

set charset => 'utf8';

get '/' => sub {

    my $dir   = Mojo::File->new( '.' );
    my @files = grep { $_ =~ /\.md/ } $dir->list_tree->each;

    my $vars = {};
    $vars->{files} = \@files;

    my $path = param 'path';
    if ( $path ) {
        my $m   = Text::Markdown->new;
        my $md  = read_file( $path, { binmode => ':utf8 ' } );
        my $doc = $m->markdown( $md );
        $vars->{doc}  = $doc;
        $vars->{path} = $path;
    }

    my $html = '';
    Template->new->process( \$template, $vars, \$html );

    return $html;
};

dance;

__DATA__
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <style>
        pre { margin-left: 2rem; }
    </style>
</head>
<body>

<div class="container mx-auto">
<div class="row">

    <div class="col-2 p-3"> 

        [% FOREACH file = files %]
        <div class="my-1 small text-truncate ">
            <a href="/?path=[% file %]">[% file %]</a>
        </div>
        [% END %]

    </div>
    <div class="col-10 p-3"> 
        <div class="text-sm mb-3">[% path %]</div>

        
        [% doc %]
    </div>

</div>
</div>

</body>
</html>
